# 站点名称
site_name: 'VisionGuide'
# 仓库链接
repo_url: https://github.com/ZJDoc/VisionGuide
# 作者
site_author: 'zhujian'
# 版权信息
copyright: '2021, zhujian'
# 源文件目录
docs_dir: 'docs'
# 生成静态文件目录
site_dir: 'site'
# 额外信息
extra:
    # 版本号
    version: 0.1.0
# 主题
theme: 
    # name: 'readthedocs'
    # name: 'mkdocs'
    name: 'material'
# markdown扩展
markdown_extensions:
  # 参考[MathJax](https://squidfunk.github.io/mkdocs-material/reference/mathjax/)，支持数学公式渲染
  - pymdownx.arithmatex:
      generic: true
    # 参考[Icons + Emojis](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/)，执行Markdown Emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# mathjax
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 导航
nav:
    - Home: index.md
    - 编程语言:
      - Python:
        - 语法: 
          - 类操作: python/grammar/类操作.md
          - 装饰器: python/grammar/装饰器.md
          - '[抽象基类]abc': python/grammar/abc.md
          - 模块和包: python/grammar/模块和包.md
          - '[py3.6][f-strings]字符串连接': python/grammar/f-strings.md
          - '[around]四舍五入': python/grammar/around.md
          - '[slice]扩展切片': python/grammar/slice.md
          - '[list]排序': python/grammar/list.md
          - '[enumerate]遍历': python/grammar/enumerate.md
          - '[itertools][product]嵌套循环': python/grammar/itertools-product.md
          - '[easydict]访问属性的方式来访问字典': python/grammar/easydict.md
          - '[collections][deque]双向队列': python/grammar/collections-deque.md
          - '[collections][defaultdict]更安全的dict': python/grammar/collections-defaultdict.md
          - '[pprint]更易读的打印': python/grammar/pprint.md
          - '[logging]日志模块': python/grammar/logging.md
          - '[tqdm]进度条': python/grammar/tqdm.md
          - '[ElementTree]读取XML文件': python/grammar/xml.md
          - '[xmltodict]读取XML文件': python/grammar/xmltodict.md
          - '[json]文件读写': python/grammar/json.md
          - '[yaml]文件读写': python/grammar/yacs.md
        - 工具:  
          - 打包和分发Python程序: ./python/tool/打包和分发Python程序.md
          - '[setup.py]保存额外数据': python/tool/setup.md
          - '[requirements.txt]依赖文件生成和使用': python/tool/requirements.md
          - '[pytest]功能测试': python/tool/pytest.md
          - '[coverage]测试代码覆盖率': python/tool/converage.md
          - '[fire]自动生成命令行界面': python/tool/fire.md
          - '[pip]更新国内镜像源': python/tool/pip.md
          - '[pnno]转换json/dict数据为voc-xml': python/tool/pnno.md
        - ERROR: python/error.md
    - 计算框架:
      - PyTorch:
        - 引言: pytorch/index.md
        - 语法:
          - Tensor: pytorch/grammar/tensor.md
          - one-hot编码: pytorch/grammar/onehot.md
          - '[transpose][permute]维度转换': pytorch/grammar/transpose-permute.md
          - '[clamp]限制取值范围': pytorch/grammar/clamp.md
          - '[index_fill]在给定维度填充指定val': pytorch/grammar/index_fill.md
          - '[nonzero]非零元素下标': pytorch/grammar/nonzero.md
          - '[Conv][Pool]实现原理': pytorch/grammar/conv-pool.md
          - 自定义损失函数: pytorch/grammar/自定义损失函数.md
          - '[softmax]分类概率计算': pytorch/grammar/softmax.md
          - '[AdaptiveMaxPool][AdaptiveAvgPool]自适应池化层': pytorch/grammar/AdaptiveMaxPool-AdaptiveAvgPool.md
          - LeNet-5定义: pytorch/grammar/LeNet5.md
          - AlexNet定义: pytorch/grammar/AlexNet.md
        - Cuda:
          - 安装哪个版本的CUDA: pytorch/cuda/安装哪个版本的CUDA.md
          - '[CUDA_VISIBLE_DEVICES]指定哪张卡运行': pytorch/cuda/指定哪张卡运行.md
          - '[empty_cache]清空显存': pytorch/cuda/empty_cache.md
          - '[benchmark]训练加速': pytorch/cuda/benchmark.md
          - 监控显存使用: pytorch/cuda/监控显存使用.md
        - Train:
          - '[译]保存和加载模型': pytorch/train/译-保存和加载模型.md
          - 固定部分参数进行训练: pytorch/train/固定部分参数进行训练.md
          - 查询模型参数总数: pytorch/train/查询模型参数总数.md  
          - 为什么推荐使用static_dict方式保存模型: pytorch/train/为什么推荐使用static_dict方式保存模型.md
          - 加载部分预训练模型: pytorch/train/加载部分预训练模型.md
          - '[[DistributedDataParallel]分布式训练]': pytorch/train/distributeddataparallel.md
        - Tool:
          - 可视化: pytorch/tool/visualize.md
        - ERROR: pytorch/error.md
      - Numpy:
        - '提取数组中属于某一条件的数据': numpy/提取数组中属于某一条件的数据.md
        - '数据保存和加载': numpy/数据保存和加载.md
        - '增加或者减少一维': numpy/增加或者减少一维.md
        - '元素累加': numpy/元素累加.md
        - '[clip]限制取值范围': numpy/限制取值范围.md
    - 视觉库:
      - Torchvision:
        - 数据预处理: torchvision/数据预处理.md
        - '[数据归一化]均值和方差': torchvision/均值和方差.md
        - '[sampler]采样器': torchvision/采样器.md
        - 自定义采样器: torchvision/自定义采样器.md
        - '加载数据集、批量以及转换操作': torchvision/加载数据集-批量以及转换操作.md
        - 自定义数据集和预处理操作: torchvision/自定义数据集和预处理操作.md
        - ImageFolder使用: torchvision/ImageFolder.md    
        - '[ConcatDataset]连接多个数据集': torchvision/concatdataset.md
        - '[Ten Crops]多样本裁剪': torchvision/ten-crops.md
      - OpenCV:
        - 概述: opencv/index.md
        - 配置:
          - 'OpenCV 3.x':
            - 'OpenCV-3.4.2源码安装': opencv/configure/3.4.2/源码安装.md
            - 'OpenCV_Contrib-3.4.2源码安装': './opencv/configure/3.4.2/Contrib-源码安装.md'
            - 'OpenCV-3.4.2测试': opencv/configure/3.4.2/测试.md
          - 'OpenCV 4.x':
            - 'OpenCV-4.0.1安装': opencv/configure/4.0.1/安装.md
            - 'OpenCV-4.0.1测试': opencv/configure/4.0.1/测试.md
            - '[OpenCV_Contrib-4.0.1]编译OpenCV4Android': opencv/configure/4.0.1/编译OpenCV4Android.md
            - 'OpenCV-4.1.0安装': opencv/configure/4.1.0/安装.md
            - 'OpenCV-4.1.0配置及测试': opencv/configure/4.1.0/配置及测试.md
            - 'OpenCV-4.2.0安装': opencv/configure/4.2.0/安装.md
            - 'OpenCV-4.2.0配置及测试': opencv/configure/4.2.0/配置及测试.md
            - 'OpenCV-4.4.0安装': opencv/configure/4.4.0/安装.md
          - Python:
            - '[opencv-python]编译与安装': opencv/configure/python/opencv-python.md
            - '[PyCharm]解码opencv python库': opencv/configure/python/pycharm.md
            - '[OpenCV]Anaconda配置': opencv/configure/python/anaconda配置.md
          - '[SSH][OpenCV]远程图像显示': './opencv/configure/SSH-OpenCV-远程图像显示.md'
        - 处理:
          - Base:
            - 运行时间统计: opencv/process/base/运行时间统计.md
            - '[VideoWriter]保存H264/MPEG4格式MP4视频': opencv/process/base/h264-mpeg4.md
            - '[normalize]标准化数据': opencv/process/base/normalize.md
            - '[convertTo]数据转换': opencv/process/base/convertTo.md
            - '[vconcat][hconcat]按行合并以及按列合并': opencv/process/base/vconcat-hconcat.md
            - '[Point_]坐标点的保存和使用': opencv/process/base/Point_.md
            - '[Scalar_]4维向量': opencv/process/base/Scalar_.md
            - '[copyMakeBorder]添加边界': opencv/process/base/copyMakeBorder.md
            - '[cartToPolar]二维向量的大小和角度': opencv/process/base/cartToPolar.md
            - '[threshold]基本阈值操作': opencv/process/base/threshold.md
            - '[旋转][平移][缩放]仿射变换': opencv/process/base/仿射变换.md
            - 单目标追踪: opencv/process/base/单目标追踪.md
          - Filter:
              - '[filter2D]线性滤波器': opencv/process/filter/filter2d.md
              - '[Sobel]图像求导': opencv/process/filter/sobel.md
              - '[Scharr]图像求导': opencv/process/filter/scharr.md
              - '[Laplacian]图像求导': opencv/process/filter/laplacian.md
              - '[Canny]边缘检测': opencv/process/filter/canny.md
          - Feature:
            - '特征/特征检测/特征描述': opencv/process/feature/Understanding-Features.md
            - '[SIFT]特征和描述符计算': opencv/process/feature/sift.md
            - '[Brute-Force][FLANN]特征匹配': opencv/process/feature/特征匹配.md
        - 绘制:
          - '[line]绘制线段': opencv/draw/line.md
          - '[rectangle]绘制边框': opencv/draw/rectangle.md
          - '[掩码]绘制多边形': opencv/draw/fillPoly.md
          - '[text]绘制文本': opencv/draw/text.md
          - '[text]绘制中文字符': opencv/draw/绘制中文字符.md
      - Matplotlib:
        - 引言: matplotlib/引言.md
        - 属性配置: matplotlib/属性配置.md
        - 中文乱码: matplotlib/中文乱码.md
        - 绘图关键概念Figure和Axes: matplotlib/绘图关键概念Figure和Axes.md
        - 手动设置轴刻度间隔: matplotlib/手动设置轴刻度间隔.md
        - '[译]Pyplot教程': matplotlib/译-Pyplot教程.md
        - 折线图: matplotlib/折线图.md
        - 饼图: matplotlib/饼图.md
        - 散点图: matplotlib/散点图.md
        - '图像读取、显示和保存': matplotlib/图像读取-显示和保存.md
        - 3d绘图: matplotlib/3d绘图.md
        - 等高线图: matplotlib/等高线图.md
        - 矩阵显示: matplotlib/矩阵显示.md
        - y轴坐标错乱: matplotlib/y轴坐标错乱.md
