# 站点名称
site_name: 'VisionGuide'
# 仓库链接
repo_url: https://github.com/ZJDoc/VisionGuide
# 作者
site_author: 'zhujian'
# 版权信息
copyright: '2021, zhujian'
# 源文件目录
docs_dir: 'docs'
# 生成静态文件目录
site_dir: 'site'
# 额外信息
extra:
    # 版本号
    version: 0.1.0
# 主题
theme: 
    # name: 'readthedocs'
    # name: 'mkdocs'
    name: 'material'
# markdown扩展
markdown_extensions:
  # 参考[MathJax](https://squidfunk.github.io/mkdocs-material/reference/mathjax/)，支持数学公式渲染
  - pymdownx.arithmatex:
      generic: true
    # 参考[Icons + Emojis](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/)，执行Markdown Emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# mathjax
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 导航
nav:
    - Home: index.md
    - 编程语言:
      - Python:
        - 语法: 
          - 类操作: python/grammar/类操作.md
          - 装饰器: python/grammar/装饰器.md
          - '[抽象基类]abc': python/grammar/abc.md
          - 模块和包: python/grammar/模块和包.md
          - '[py3.6][f-strings]字符串连接': python/grammar/f-strings.md
          - '[around]四舍五入': python/grammar/around.md
          - '[slice]扩展切片': python/grammar/slice.md
          - '[list]排序': python/grammar/list.md
          - '[enumerate]遍历': python/grammar/enumerate.md
          - '[itertools][product]嵌套循环': python/grammar/itertools-product.md
          - '[easydict]访问属性的方式来访问字典': python/grammar/easydict.md
          - '[collections][deque]双向队列': python/grammar/collections-deque.md
          - '[collections][defaultdict]更安全的dict': python/grammar/collections-defaultdict.md
          - '[pprint]更易读的打印': python/grammar/pprint.md
          - '[logging]日志模块': python/grammar/logging.md
          - '[tqdm]进度条': python/grammar/tqdm.md
          - '[ElementTree]读取XML文件': python/grammar/xml.md
          - '[xmltodict]读取XML文件': python/grammar/xmltodict.md
          - '[json]文件读写': python/grammar/json.md
          - '[yaml]文件读写': python/grammar/yacs.md
        - 工具:  
          - 打包和分发Python程序: ./python/tool/打包和分发Python程序.md
          - '[setup.py]保存额外数据': python/tool/setup.md
          - '[requirements.txt]依赖文件生成和使用': python/tool/requirements.md
          - '[pytest]功能测试': python/tool/pytest.md
          - '[coverage]测试代码覆盖率': python/tool/converage.md
          - '[fire]自动生成命令行界面': python/tool/fire.md
          - '[pip]更新国内镜像源': python/tool/pip.md
          - '[pnno]转换json/dict数据为voc-xml': python/tool/pnno.md
        - ERROR: python/error.md
    - 计算框架:
      - Numpy:
        - '提取数组中属于某一条件的数据': numpy/提取数组中属于某一条件的数据.md
        - '数据保存和加载': numpy/数据保存和加载.md
        - '增加或者减少一维': numpy/增加或者减少一维.md
        - '元素累加': numpy/元素累加.md
        - '[clip]限制取值范围': numpy/限制取值范围.md
    - 视觉库:
      - Matplotlib:
        - 引言: matplotlib/引言.md
        - 属性配置: matplotlib/属性配置.md
        - 中文乱码: matplotlib/中文乱码.md
        - 绘图关键概念Figure和Axes: matplotlib/绘图关键概念Figure和Axes.md
        - 手动设置轴刻度间隔: matplotlib/手动设置轴刻度间隔.md
        - '[译]Pyplot教程': matplotlib/译-Pyplot教程.md
        - 折线图: matplotlib/折线图.md
        - 饼图: matplotlib/饼图.md
        - 散点图: matplotlib/散点图.md
        - '图像读取、显示和保存': matplotlib/图像读取-显示和保存.md
        - 3d绘图: matplotlib/3d绘图.md
        - 等高线图: matplotlib/等高线图.md
        - 矩阵显示: matplotlib/矩阵显示.md
        - y轴坐标错乱: matplotlib/y轴坐标错乱.md